### ISSUE TITLE
as!anilist <username> sometimes returns error when searching valid username 

### ISSUE THREAD

**Issue by raphaelsero** [IchBinLeoon/anisearch-discord-bot#2]
https://anilist.co/user/hiiraph/
![2020-10-16_10-53-45](https://user-images.githubusercontent.com/16494146/96292132-f59e3380-0f9d-11eb-9685-4fd52b9d1eab.png)

**Comment by IchBinLeoon** [comment]
Should work now.
![fix](https://user-images.githubusercontent.com/50367411/96296022-e4c9de00-0fee-11eb-989f-067ad3c9cf27.PNG)
