### ISSUE TITLE
Error With Website

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [IchBinLeoon/anisearch-discord-bot#23]
I don't know how to describe this bug, but your website has a bug with its navbar.
<img width="1280" alt="Screen Shot 2021-05-05 at 5 02 58 PM" src="https://user-images.githubusercontent.com/70828596/117209111-ee1c6b80-adc3-11eb-96e8-20c45074f1f6.png">

**Comment by Isaiah-Hamilton** [comment]
My pr #24 fixes this problem.

**Comment by IchBinLeoon** [comment]
Thanks for mentioning the error!
