### ISSUE TITLE
Character command missing appropriate spoiler tags

### ISSUE THREAD

**Issue by abhishekd-1** [IchBinLeoon/anisearch-discord-bot#8]
When looking for a character on Anilist, the part of the description that is a spoiler is hidden. Discord also has spoiler tag functionality by enclosing a portion of the message with a double pipe || . AniList's API encloses it with ~!Spoiler Text!~ which does nothing in Discord... If you could just change that to ||Spoiler Text||, that would be really awesome since nobody likes spoilers :P

Please do not remove the spoilers completely, as lots of bots do that! I am looking for a bot that keeps the spoilers in the embedded message, but hides them with Discord's spoiler tags.

If you need example characters, you could use "Dio Brando" (from Jojo's Bizzare Adventures) or "Rem" (from Re:Zero). I'd be happy to provide any more info that you need!

**Comment by IchBinLeoon** [comment]
Hello there, like you said, nobody likes spoilers, neither I do. Spoiler tags have now been added to the embeds.

![dioex](https://user-images.githubusercontent.com/50367411/103175132-06093f00-4868-11eb-80b0-f1f79b957c9f.PNG)
![remex](https://user-images.githubusercontent.com/50367411/103175134-06a1d580-4868-11eb-8b91-ba116fcc6a33.PNG)
![riasex](https://user-images.githubusercontent.com/50367411/103175135-06a1d580-4868-11eb-9aa1-17beb11042e2.PNG)

**Comment by abhishekd-1** [comment]
Thanks a lot for this change!
